### ISSUE TITLE
Is there a way to make it seedable?

### ISSUE THREAD

**Issue by RicardRC** [joeclark-phd/markov_namegen#1]
I've been trying to get this crate and multimarkov crate to work as seedable, but there's some source of indeterminism, even using .without_prior(), within the crate. Could you point where it might be coming from?

**Comment by joeclark-phd** [comment]
Done.  Thanks to your change to `multimarkov` I was able to update this crate to take a custom RNG.  Use version "3.1" or higher, and look at the README for the usage.  I updated the builder, adding an optional method `with_rng()`.
